### ISSUE TITLE
Updater / Referral Deploy Checklist Template

### ISSUE THREAD

**Issue by aekeus** [brave/vault-updater#124]
### Scope

- [ ] Fastly VCL
- [ ] Updater
- [ ] Referral

### Type

- [ ] Configuration
- [ ] Code

### Pre-deploy

- [ ] Code reviews complete
- [ ] Deployed and tested in staging environment
- [ ] Updater unit tests passing
- [ ] Referral unit tests passing

### Post-deploy

- [ ] Organic download links working on brave.com
- [ ] Referral download links working on brave.com
- [ ] Usage records capturing in mlab
- [ ] Referral records capturing in Heroku Postgres

**Comment by aekeus** [comment]
cc @keur @w0ts0n @corymcdonald @bkero @mihaiplesa

**Comment by w0ts0n** [comment]
Looks good to me.
