### ISSUE TITLE
Deploy checklist - 2020-03-27

### ISSUE THREAD

**Issue by aekeus** [brave/vault-updater#131]
#### Fastly

- [ ] VCL

#### Updater
- [x] Code
- [ ] DDL
- [ ] Configuration

#### Referral Promo Server
- [ ] Code
- [ ] DDL
- [ ] Configuration

### Pre-deploy

- [x] Code reviews complete
- [x] Deployed and tested in staging environment
- [x] Updater unit tests passing
- [x] Referral unit tests passing

### Post-deploy

- [x] Organic download links working on brave.com
- [x] Referral download links working on brave.com
- [x] Usage records capturing in mlab
- [x] Referral records capturing in Heroku Postgres

**Comment by aekeus** [comment]
cc @keur
